name: Build & Deploy

on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb && sudo dpkg -i pandoc-2.7.2-1-amd64.deb
    - name: Build page
      run: bash build.sh
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: success() && github.ref == 'refs/heads/master'
      with: 
        publish_dir: ./docs
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        cname: bitcoincoredocs.com
